### ISSUE TITLE
Autoprefixer option {remove: false} is ignored/broken?

### ISSUE THREAD

**Issue by rejhgadellaa** [sindresorhus/gulp-autoprefixer#101]
Gulp-autoprefixer removes the `-webkit-box-orient: vertical;` property from my css.

I tried using the "remove" option, setting it to false: `.pipe(autoprefixer({remove: false})` but that doesn't seem to work.

Is this broken?

Update: right, version numbers..
gulp 4.0
gulp-autoprefixer 5.0.0

**Comment by sindresorhus** [comment]
This plugin just passes your options directly to Autoprefixer, so the issue must be there. Maybe related to https://github.com/postcss/autoprefixer/issues/1014
