### ISSUE TITLE
IE 11 input placeholder styling problem

### ISSUE THREAD

**Issue by lohmatyi** [sindresorhus/gulp-autoprefixer#102]
According to [this stackoverflow issue](https://stackoverflow.com/questions/22199047/placeholder-css-not-being-applied-in-ie-11) IE 11 needs '!important' flag for rules inside his ':-ms-input-placeholder' pseudo-selector.
For me the problem wasn't visible on development server but is on production.

**Comment by sindresorhus** [comment]
From the readme:

> *Issues with the output should be reported on the Autoprefixer [issue tracker](https://github.com/postcss/autoprefixer/issues).*
