### ISSUE TITLE
Browserlist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by briankoudijs** [sindresorhus/gulp-autoprefixer#110]
Getting this warning: `Browserslist: caniuse-lite is outdated. Please run next command 'npm update caniuse-lite browserslist'` on running Gulp task. 

![image](https://user-images.githubusercontent.com/751817/54519844-bf36a780-4967-11e9-97fa-1e6e65e64ea2.png)

**Comment by jhonnyizidoro** [comment]
I was getting the same warning. I installed the `prefixer` package and then uninstalled. Maybe a common file between the `autoprefixer` and `gulp-autoprefixer` was updated in this proccess.

I guess this is a temporary fix for the warning.

**Comment by briankoudijs** [comment]
@jhonnyizidoro Thanks for your reply. Yesterday I installed `autoprefixer` and removed `gulp-autoprefixer`
