### ISSUE TITLE
Update to latest autoprefixer

### ISSUE THREAD

**Issue by adamreisnz** [sindresorhus/gulp-autoprefixer#116]
@sindresorhus Can you please release a new version of this plugin with the latest autoprefixer version, so we can get rid of this warning:

`Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade``

Thanks.

**Comment by sindresorhus** [comment]
There's nothing to update. The semver range defined here still matches the latest. **You** have to update your lockfile.
