### ISSUE TITLE
It not supporting in GULP environment

### ISSUE THREAD

**Issue by aditya305** [sindresorhus/gulp-autoprefixer#120]
After updating it's not supporting to the GulpJS

showing error after updating to the to version: 9.0.0

```
Instead change the require of index.js in C:\Users\adity\OneDrive\Documents\GitHub\flutter-jobs-official-2023\gulpfile.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\adity\OneDrive\Documents\GitHub\flutter-jobs-official-2023\gulpfile.js:3:22) {
  code: 'ERR_REQUIRE_ESM'
}
```

Its perfectly working with:

`
"gulp-autoprefixer": "^8.0.0",`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by aditya305** [comment]
The problem persists; I am unable to transition to version 9 at this time.
