### ISSUE TITLE
linear-gradient not compiling correctly

### ISSUE THREAD

**Issue by msisto** [sindresorhus/gulp-autoprefixer#23]
I am observing what seems to be a bug from an older vesrion of Autoprefixer in the current version of gulp-autoprefixer (2.0.0). Everything else is working a-OK.

**Source**
`background: linear-gradient(45deg, #517EA3, #326B9C);`

**Output**
`background: linear, 45deg, #517EA3, #326B9C;`

Related:
http://stackoverflow.com/questions/23340586/wrong-autoprefixer-compilation-on-linear-gradient

**Comment by sindresorhus** [comment]
Reinstall this task to get the latest Autoprefixer version.

**Comment by msisto** [comment]
This is w/ Autoprefixer 4.0.2.

```
  "name": "autoprefixer-core",
  "version": "4.0.2",
```

**Comment by sindresorhus** [comment]
So why are you opening an issue here? 

https://github.com/postcss/autoprefixer-core/issues/new
