### ISSUE TITLE
Perspective Bug (with firefox)

### ISSUE THREAD

**Issue by Paolocargnin** [sindresorhus/gulp-autoprefixer#24]
Hi, I've a problem with the autoprefixer in the Transform property.

With this auto-prefixer configuration:
		.pipe(autoprefixer('last 2 version', 'safari 5',  'Firefox ESR', 'opera 12.1'))

If I write :

>		transform: perspective(300px) rotateX(-90deg);

The result is:

transform:perspective(300) rotateY(-90deg);

I don't understand why it removes the "px" units, with firefox it doesn't read the property.

Maybe there is a work around? 

Thanks

Paolo

**Comment by sindresorhus** [comment]
Read the readme.
