### ISSUE TITLE
Why use this rather than autoprefixer's suggested gulp task?

### ISSUE THREAD

**Issue by cappslock** [sindresorhus/gulp-autoprefixer#25]
Not trying to be rude, just curious. Why would someone use this plugin rather than [autoprefixer's suggested gulp task](https://github.com/postcss/autoprefixer#gulp)?

**Comment by sindresorhus** [comment]
If you only need Autoprefixer and no other PostCSS transforms which applies to most users, this is easier to use and requires less code. But doesn't really matter much.

**Comment by cappslock** [comment]
Fair enough, thanks.
