### ISSUE TITLE
@-moz-document url-prefix() breaks autoprefixer

### ISSUE THREAD

**Issue by mvanleest** [sindresorhus/gulp-autoprefixer#27]
any css file with @-moz-document url-prefix() in it will break the gulp-autoprefixer.

try to process this piece of css:

```
@-moz-document url-prefix() {
	.test {
		background: url('/inc/img/ui/caret.png') right 5px center no-repeat);
		background-size: 12px 12px;
	}
}
```

And my gulp task looks like:

```
gulp.task('testcss', function() {
  return gulp.src([
    'inc/css/test.css'])
  .pipe(autoprefixer('> 1%','last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1'))
  .pipe(concat('test.min.css'))
    .pipe(minifycss({keepBreaks:false}))
    .pipe(gulp.dest(DEST+'css'))
    .pipe(notify({message: 'CSS stylesheets task complete'}));
});
```

Any idea what this might be? looking at autoprefixer-core, this issue is resolved. So maybe gulp-autoprefixer is using old core code?

**Comment by sindresorhus** [comment]
Try reinstalling this task.

**Comment by mvanleest** [comment]
I reinstalled all the packages with the latest version, but no luck.
Might be worth looking into as it makes the package unusable. Will switch over to something else for now.

**Comment by sindresorhus** [comment]
The issue is not here at least. It's using the latest autoprefixer.
