### ISSUE TITLE
Sass + Autoprefixer + Sourcemaps

### ISSUE THREAD

**Issue by MethodGrab** [sindresorhus/gulp-autoprefixer#30]
If you have unicode **symbols** anywhere in your Sass (eg: pseudo element `content` property), it will cause the sourcemap to not appear in Chrome when using `gulp-sourcemaps` with `gulp-sass` + `gulp-autoprefixer`.

It seems to be just the symbols, if you replace them with hex representations then sourcemaps work.
It also appears to be autoprefixer related as compiling **with** symbols but **without** autoprefixer **does** show the sourcemap correctly.

I made a reduced test case which demonstrates the issue and has more detail here [MethodGrab/gulp-sourcemaps-test-case](https://github.com/MethodGrab/gulp-sourcemaps-test-case).

Possibly related: https://github.com/sindresorhus/gulp-autoprefixer/issues/8

**Comment by sindresorhus** [comment]
Please read the readme. Should be opened at the autoprefixer issue tracker.
