### ISSUE TITLE
2.1.0 breaks auto-prefixing flexbox on Safari 8.0.5

### ISSUE THREAD

**Issue by matiasvad** [sindresorhus/gulp-autoprefixer#31]
Output of `display: flex;` on Safari 8.0.5 is `display:-webkit-box` and not `display:-webkit-flex`, thus not working.

Downgrading to 2.0.0 fixes issue. 

Config: `.pipe(autoprefixer('last 2 version', 'ie 10', 'ios 7'))`

**Comment by kevva** [comment]
> Issues with the output should be reported on the Autoprefixer [issue tracker](https://github.com/postcss/autoprefixer-core/issues).
