### ISSUE TITLE
Sourcemaps with gulp-sass on windows

### ISSUE THREAD

**Issue by JosephSilber** [sindresorhus/gulp-autoprefixer#38]
When trying to get sourcemaps for sass + autoprefixer on Windows, the resulting sourcemap's `contentSource` is the compiled CSS, not the original sass.

```js
var autoprefixer = require('gulp-autoprefixer');
var gulp = require('gulp');
var rename = require('gulp-rename');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('css', function () {
    gulp.src('resources/assets/sass/app.scss')
        .pipe(sourcemaps.init())
        .pipe(sass({ outputStyle: 'compressed' }))
        .pipe(autoprefixer())
        .pipe(rename('css/app.css'))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('public'));
});
```

Removing `autoprefixer` from the stream results in proper sourcemaps.

---

For more context, see here: http://stackoverflow.com/questions/30805146

---

To test this on a Windows machine, download this: [gulp-sass-autoprefixer-sourcemaps.zip](gulp-sass-autoprefixer-sourcemaps.zip).

Unzip, and run: `npm install && gulp css`.

**Comment by sindresorhus** [comment]
There's a lot of existing tickets about this. It's a problem with gulp-sass. Apparently gulp-sass 2.0 (unreleased) will fix this. Though not the right place to discuss this.
