### ISSUE TITLE
Update to use autoprefixer-core 5.x

### ISSUE THREAD

**Issue by PCateNumbersUSA** [sindresorhus/gulp-autoprefixer#39]
Seems like the autoprefixer-core is in the 5.x release range: https://github.com/postcss/autoprefixer-core/releases

My understanding is that gulp-autoprefixer is using the 4.x core so it would be nice to see an update.

**Comment by sindresorhus** [comment]
You could have easily checked: https://github.com/sindresorhus/gulp-autoprefixer/blob/02d77661de48890facdf98e1061400264d4f5ef8/package.json#L33 ...
