### ISSUE TITLE
Running the test

### ISSUE THREAD

**Issue by mhdSid** [sindresorhus/gulp-autoprefixer#41]
Hello, I have a repo about a gulp-project-automation. But I'm having trouble to run a test on this gulp file. How were you able to test this gulp file? I'm using karma/jasmine runs the test in the browser. In addition, I used browserify to access and require modules from within the browser like (gulp, should, assert). But when I run the test, it throws undefined error and the instruction where I'm using module name says name is not a function..

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gulp
