### ISSUE TITLE
Error: no writecb in Transform class

### ISSUE THREAD

**Issue by Soviut** [sindresorhus/gulp-autoprefixer#46]
I'm getting `Error: no writecb in Transform class` with gulp-autoprefixer version 3.0.2 on Node 0.10 using the following task:

```coffeescript
gulp.task 'styles', ->
    gulp.src "#{src.styles}/**/*.styl"
        .pipe plumber()
        .pipe stylus 
            use: nib()
        .pipe autoprefixer 
            browsers: ['last 2 versions']
        .pipe gulp.dest dest.styles
```

**Comment by Shutnik** [comment]
I have same problem.

**Comment by sindresorhus** [comment]
Node 0.10 is no longer supported. 3.0.0 was a major release for a reason. Upgrade Node.

**Comment by bugsancho** [comment]
I'm getting the same error using gulp-autoprefixer(3.0.2) with gulp-less(3.0.3) on node 0.12.
Code looks like this:
```javascript
    return gulp.src(sources.styles)
      .pipe(less())
      .pipe(cssAutoPrefixer({browsers: ['last 2 versions']}))
      .pipe(gulp.dest(config.buildDirectory));
```

**Comment by betaorbust** [comment]
@sindresorhus, as there's no changelog, can you put this in the [release notes for 3](https://github.com/sindresorhus/gulp-autoprefixer/releases)?
`no writecb in Transform class` is an unfortunately common error, and it took a while to track down that it was gulp-autoprefixer throwing it.
Putting depreciations or breaking changes between major releases would be AWESOME and would make keeping our packages up to date much easier.

**Comment by sindresorhus** [comment]
Done, but just to be clear, the breaking change with dropping support for Node.js 0.10 was in `autoprefixer`, not this plugin. That's where the notice should have been.

**Comment by wesleypimentel** [comment]
I solved my issue by changing the way how declaring CSS animations with @keyframes in LESS file. The problem was related with the "quotes" around the animation name. If anyone is interested, please read this other comment.

[https://github.com/plus3network/gulp-less/issues/207#issuecomment-247531472](url)
