### ISSUE TITLE
Unhandled error or source map sources are lost

### ISSUE THREAD

**Issue by clee704** [sindresorhus/gulp-autoprefixer#47]
Reproduction scenario:

    git clone https://github.com/clee704/gulp-autoprefixer-test.git
    cd gulp-autoprefixer-test
    npm install
    git checkout error
    gulp css  # Unhandled 'error' event
    git checkout lost
    gulp css
    head -c 200 build/css/app.css.map  # "sources" array is incomplete
    git checkout works
    gulp css
    head -c 200 build/css/app.css.map  # correct "sources"

Seems like gulp-autoprefixer is handling source maps incorrectly or other modules (gulp-sass or gulp-sourcemaps) are not doing their jobs right.

**Comment by sindresorhus** [comment]
This is most likely a problem with `gulp-sass`. Look at the closed issues for previous discussions.

Maybe relevant: https://github.com/dlmanning/gulp-sass/issues/354
