### ISSUE TITLE
gulp-autoprefixer seems to work differently on OS X and Windows 7

### ISSUE THREAD

**Issue by ol-ko** [sindresorhus/gulp-autoprefixer#59]
Hi, I'm having an issue with different prefixes being added by running same version of gulp-autoprefixer (2.2.0) on OS X (El Capitan) and Windows 7 with the 'last 2 version' setting.

SCSS:
`a {
	transform: rotate(-5);
}`

OS X CSS:
`a {
  -webkit-transform: rotate(-5);
          transform: rotate(-5); }`

Windows CSS:
`a {
  -webkit-transform: rotate(-5);
          -ms-transform: rotate(-5);
                  transform: rotate(-5); }`

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the Autoprefixer [issue tracker](https://github.com/postcss/autoprefixer/issues).*
