### ISSUE TITLE
Mention about possibility to use postCSS instead

### ISSUE THREAD

**Issue by simison** [sindresorhus/gulp-autoprefixer#62]
While this plugin is great if one doesn't need anything else but autoprefixing, I'm kinda missing information from readme which would suggest to use `postcss` autoprefixer plugin instead:
https://github.com/postcss/autoprefixer#gulp

Using `postcss` seems to be recommended way by the Gulp team anyway:
https://github.com/gulpjs/plugins/issues/210

Now people might be adding CSS minifiers and autoprefixers separately to their build scripts, while they really should be adding postfix with these plugins instead.

Thoughts?

**Comment by simison** [comment]
Now, a bit more neutral title. :-)

**Comment by sindresorhus** [comment]
Sure. PR welcome.

**Comment by simison** [comment]
Aight! ^ Just scribbled something.
