### ISSUE TITLE
transform property not getting prefixed

### ISSUE THREAD

**Issue by thykka** [sindresorhus/gulp-autoprefixer#64]
So i've been using the same gulp setup for many months, but today as I was updating an old project, I noticed it doesn't look right on Android (4.2). Turned out the compiled css was missing -webkit prefix for the transform property (which previously did receive the prefix as it should).

According to caniuse, this prefix is needed for all pre-5 Androids.

Here's my gulpfile and a simple test case, which demostrates the issue:
https://gist.github.com/thykka/b450db9742246245818807d7642e9247

There is no issue when using the same settings with the [online autoprefixer](https://autoprefixer.github.io/) though, which leads me to believe this problem is specific to either my config or gulp-autoprefixer itself.

Any ideas?

**Comment by SamVerschueren** [comment]
From the Readme

> Issues with the output should be reported on the Autoprefixer [issue tracker](https://github.com/postcss/autoprefixer/issues).

`gulp-autoprefixer` just calls `autoprefixer`. So if something is wrong, it should be reported to that repository.

**Comment by thykka** [comment]
Turns out my problem was caused by giving the browser versions as multiple arguments

    .pipe(autoprefixer('last 2 versions', 'android 4'))

...instead of a single array

    .pipe(autoprefixer(['last 2 versions', 'android 4']))
