### ISSUE TITLE
Flexbox duplicate property in Safari 9.1.2

### ISSUE THREAD

**Issue by GavinJaynes** [sindresorhus/gulp-autoprefixer#69]
Hi I'm using - the latest version of gulp-autoprefixer - 3.1.1 and in Safari 9.1.2 Flexbox does not render because it says there are duplicate properties. 

display: -webkit-box;
display: flex;

if I turn off display:flex it works. This seems like a Safari issue more than an autoprefixer issue but is there and override or some work around. 

Any suggestions appreciated

**Comment by GavinJaynes** [comment]
For anyone who is interested the problem can be solved with CSS @supports is  pretty well supported. 


`@supports( display:flex ) {
	display: flex;
	flex-wrap: wrap;
	flex-direction: row-reverse;
}

@supports not ( display:flex ) {
	display: -webkit-box;
	flex-wrap: wrap;
	flex-direction: row-reverse;
}`

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the Autoprefixer [issue tracker](https://github.com/postcss/autoprefixer/issues).*
