### ISSUE TITLE
-ms prefix not added to transform in some cases

### ISSUE THREAD

**Issue by orest22** [sindresorhus/gulp-autoprefixer#70]
Hi, I'm using version 3.1.1 with configuration `['last 2 versions', 'ie >= 9']` and it doesn't work for me. Here is an code example:
```
.transform-translate-x-z {
  transform: translateX(-50%) translateZ(0);
  transition: all .2s;
  &.multi-transform {
    transform: rotate(15deg) translate(-20px, 0px);
  }
}
```
Transformed in:
```
.transform-translate-x-z {
  transform: translateX(-50%) translateZ(0);
  transition: all .2s;
 }
.transform-translate-x-z.multi-transform {
    -ms-transform: rotate(15deg) translate(-20px, 0px);
        transform: rotate(15deg) translate(-20px, 0px); 
}
```

What I'm doing wrong? Thanks in advance!

**Comment by battaglr** [comment]
From the top of the readme:

> *Issues with the output should be reported on the Autoprefixer [issue tracker](https://github.com/postcss/autoprefixer/issues).*

**Comment by orest22** [comment]
@battaglr Sorry I've noticed it after. Thanks.
