### ISSUE TITLE
Issues when using KSS styleguide generator

### ISSUE THREAD

**Issue by mtuller** [sindresorhus/gulp-autoprefixer#71]
When I use the autoprefixer on a page that I have KSS styleguide setup, I get the following error.

events.js:141
      throw er; // Unhandled 'error' event
      ^
CssSyntaxError: C:\Users\t910636\Desktop\tcf-frontend\styles\scss\default\_vars.scss:14:4: Missed semicolon
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser  12 | //--------------------------------------
  13 |
> 14 | // Colors
     |    ^

This is with the following commented text.

// Colors
//
// The colors for the site
//
//
// Markup: <a href="http://www.tcfbank.com/" target="">A Link</a>
//
// Styleguide 1

//--------------------------------------
// VARIABLES
//--------------------------------------

Once I remove the call to the autoprefixer, it all runs fine.

**Comment by sindresorhus** [comment]
Open an issue on the generator you used. This is an issue tracker, not support forum.

**Comment by mtuller** [comment]
The generator works. What happens is when I have the markup as shown above, the autoprefixer give me an error. So this is something to do with the autoprefixer, not the styleguide generator.

**Comment by sindresorhus** [comment]
> You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

As the error says and the readme here clear points out, this plugin only supports CSS, not SCSS. SCSS could be added, but not something that is supported now. So, yes, it's a support question.
