### ISSUE TITLE
npm installation fails

### ISSUE THREAD

**Issue by ericsoco** [sindresorhus/gulp-autoprefixer#73]
Getting an unhelpful/generic error from npm (`npm ERR! cb() never called!`).

Repro:
```
mkdir temp
cd temp
npm init
npm i gulp-autoprefixer
```

**Comment by ericsoco** [comment]
I'm on `node@5.9.1`, `npm@4.0.5`. Report on other thread says `npm@4.1.1` works, trying now.

**Comment by ericsoco** [comment]
And FWIW `gulp-autoprefixer@2.3.1` installs properly on above node/npm versions. `v3.0.0` and above fail.

**Comment by ericsoco** [comment]
Updating to `npm@4.1.1` did not fix for me. I'm ok working against `gulp-autoprefixer@2.3.1` for now.

**Comment by sindresorhus** [comment]
Install issues should be reported to npm.
