### ISSUE TITLE
-webkit-box-orient: vertical; is getting removed in the final css file

### ISSUE THREAD

**Issue by maruthi1255** [sindresorhus/gulp-autoprefixer#74]
Hi,
 My sass file is as follows.
{
      overflow : hidden;
      text-overflow: ellipsis;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical; }

We are using gulp-autoprefixer while compressing the css files.
In the final css file the -webkit-box-orient: vertical property is missing.
Could you please help me to resolve this issue.

**Comment by sindresorhus** [comment]
Autoprefixer removes outdated prefixes that are no longer needed. 

https://github.com/postcss/autoprefixer#options

**Comment by maruthi1255** [comment]
Thanks for update.

Do we have any option to disable this behaviour.
This was working earlier. Not sure when this feature got removed.
Is there any workaround for this.

**Comment by maruthi1255** [comment]
autoprefixer({browsers: ['last 2 version'] , remove: false}
This is working.
Thanks
