### ISSUE TITLE
last 3 versions

### ISSUE THREAD

**Issue by sudeep494** [sindresorhus/gulp-autoprefixer#78]
There seems to be an issue with 'last 3 versions' with upgrade to 3.1.1?
**Specific issue**: last 3 versions used to add -webkit- prefix for display:flex pre 3.1.1
After upgrade to 3.1.1 it does not. If you specificly specify 'safari 8' in the browser list query, it works in 3.1.1

safari is in current version of 10 so ideally last 3 versions should have worked for safari 8  in case of display:flex. Infact it did use to work before upgrade to 3.1.1
Unfortunately i do not know what version I was running before the upgrade to 3.1.1

**Comment by billyjov** [comment]
@sudeep494 if you want to have `-webkit-` prefixes e.g you should specify which last 3 versions you need.

see here [Browserlist for autoprefixer](https://github.com/ai/browserslist) .
And it's specify in the *README.md* how to use it.

**Comment by kevva** [comment]
http://browserl.ist/?q=last+3+versions

You'd have to write `{browsers: ['last 3 versions', 'safari >= 8']}` or likewise.
