### ISSUE TITLE
Last two versions can not add -webkit prefixes

### ISSUE THREAD

**Issue by billyjov** [sindresorhus/gulp-autoprefixer#79]
As long as you use this config the -webkit prefixes can not be added.

`.pipe(autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        })`

Only *-ms* prefixes will be added.

**Comment by sindresorhus** [comment]
It only adds prefixes when needed. I guess the `last 2 versions` doesn't need those prefixes.

**Comment by billyjov** [comment]
@sindresorhus is there a way to add these prefixes too ? How can I set my config ?

**Comment by sindresorhus** [comment]
You change the `browsers` config to the browsers you want to support. It's all documented in the readme.
