### ISSUE TITLE
TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by amlbar** [sindresorhus/gulp-autoprefixer#83]
I always get the error above. How can I fix this?

I could not make the script below to work:

```js
const gulp = require('gulp');
const autoprefixer = require('gulp-autoprefixer');

gulp.task('default', () =>
    gulp.src('src/app.css')
        .pipe(autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        }))
        .pipe(gulp.dest('dist'))
);
```

gulp -v
CLI version 1.3.0
Local version 3.9.1

npm -v
3.10.6

node -v
v4.3.0

**Comment by andavies** [comment]
@amlbar I've been struggling with the same issue today. All you need to do is update your version of node to the latest stable build (7.10.0). (At least this fixed the issue for me.)

**Comment by mach1media** [comment]
Thank you @amlbar, this was driving me crazy on all projects I started within the past few weeks, and I couldn't find any explanation until your response.

**Comment by kevva** [comment]
Yes, we use `Buffer.from` [here](https://github.com/sindresorhus/gulp-autoprefixer/blob/master/package.json#L13) which was introduced in Node.js 4.5, hence the version requirement here https://github.com/sindresorhus/gulp-autoprefixer/blob/master/package.json#L13.

**Comment by webmasterpf** [comment]
Upgrading to nodeJS 6.1 fix the error.

**Comment by davidbru** [comment]
I can confirm that autoprefixer 4.0.0 does not work with node 5.4.1.
After updating node to version 6.11.1 it worked again

**Comment by philharmonie** [comment]
I'm on node 8.2.1 and I'm having the issue. Any solution?

**Comment by aquamoth** [comment]
@philharmonie I had the same issue. Turns out VS didn't use the latest node version, which I verified by printing out process.version inside my gulp task. Just follow these steps to ensure you run the correct version: https://stackoverflow.com/questions/43849585/update-node-version-in-visual-studio-2017

**Comment by browserfiles** [comment]
this is the only plugin in the gulp tasks that generates an error, still no go:
![image](https://user-images.githubusercontent.com/20356637/31494448-eb47086a-af85-11e7-86c1-5d21e3445bee.png)
