### ISSUE TITLE
"TypeError: this is not a typed array", Gulp error, help me

### ISSUE THREAD

**Issue by richred** [sindresorhus/gulp-autoprefixer#84]
Hello!
Day ago I moved to Ubunutu from Windows 10 and only now I started configuring gulp for web development.
Faced such a problem when start gulp:

`[15:31:33] Starting 'sass'...
[15:31:33] Starting 'common-js'...
[15:31:33] Starting 'browser-sync'...
[15:31:33] Finished 'browser-sync' after 48 ms
[15:31:33] Finished 'common-js' after 92 ms
[15:31:33] Starting 'js'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at /media/richard/HDD/General/web/_dev/gulp.com/node_modules/gulp-autoprefixer/index.js:25:27
    at process._tickCallback (node.js:356:9)`

![screenshot from 2017-07-09 14-03-53](https://user-images.githubusercontent.com/26653363/27994030-0e3e80ae-64be-11e7-9e92-50cad8b92598.png)

my gulpfile.js
![screenshot from 2017-07-09 15-54-44](https://user-images.githubusercontent.com/26653363/27994089-013269c4-64bf-11e7-9b43-25be531e2000.png)

`var gulp           = require('gulp'),
		gutil          = require('gulp-util' ),
		sass           = require('gulp-sass'),
		browserSync    = require('browser-sync'),
		concat         = require('gulp-concat'),
		uglify         = require('gulp-uglify'),
		cleanCSS       = require('gulp-clean-css'),
		rename         = require('gulp-rename'),
		del            = require('del'),
		imagemin       = require('gulp-imagemin'),
		cache          = require('gulp-cache'),
		autoprefixer   = require('gulp-autoprefixer'),
		ftp            = require('vinyl-ftp'),
		notify         = require("gulp-notify");

gulp.task('common-js', function() {
	return gulp.src([
		'app/js/common.js',
		])
	.pipe(concat('common.min.js'))
	.pipe(uglify())
	.pipe(gulp.dest('app/js'));
});

gulp.task('js', ['common-js'], function() {
	return gulp.src([
		'app/libs/jquery/dist/jquery.min.js',
		'app/js/common.min.js', // Всегда в конце
		])
	.pipe(concat('scripts.min.js'))
	.pipe(uglify()) 
	.pipe(gulp.dest('app/js'))
	.pipe(browserSync.reload({stream: true}));
});

gulp.task('browser-sync', function() {
	browserSync({
		proxy: 'http://localhost/app',
		notify: false,
		// tunnel: true,
		// tunnel: "projectmane",
	});
});

gulp.task('sass', function() {
	return gulp.src('app/sass/**/*.sass')
	.pipe(sass({outputStyle: 'expand'}).on("error", notify.onError()))
	.pipe(rename({suffix: '.min', prefix : ''}))
	**.pipe(autoprefixer(['last 15 versions']))**
	// .pipe(cleanCSS()) 
	.pipe(gulp.dest('app/css'))
	.pipe(browserSync.reload({stream: true}));
});

gulp.task('watch', ['sass', 'js', 'browser-sync'], function() {
	gulp.watch('app/sass/**/*.sass', ['sass']);
	gulp.watch(['libs/**/*.js', 'app/js/common.js'], ['js']);
	gulp.watch('app/*.php', browserSync.reload);
});

gulp.task('imagemin', function() {
	return gulp.src('app/img/**/*')
	.pipe(cache(imagemin()))
	.pipe(gulp.dest('dist/img')); 
});

gulp.task('build', ['removedist', 'imagemin', 'sass', 'js'], function() {

	var buildFiles = gulp.src([
		'app/*.html',
		'app/.htaccess',
		]).pipe(gulp.dest('dist'));

	var buildCss = gulp.src([
		'app/css/main.min.css',
		]).pipe(gulp.dest('dist/css'));

	var buildJs = gulp.src([
		'app/js/scripts.min.js',
		]).pipe(gulp.dest('dist/js'));

	var buildFonts = gulp.src([
		'app/fonts/**/*',
		]).pipe(gulp.dest('dist/fonts'));

});

gulp.task('deploy', function() {

	var conn = ftp.create({
		host:      'hostname.com',
		user:      'username',
		password:  'userpassword',
		parallel:  10,
		log: gutil.log
	});

	var globs = [
	'dist/**',
	'dist/.htaccess',
	];
	return gulp.src(globs, {buffer: false})
	.pipe(conn.dest('/path/to/folder/on/server'));

});

gulp.task('removedist', function() { return del.sync('dist'); });
gulp.task('clearcache', function () { return cache.clearAll(); });

gulp.task('default', ['watch']);
`
it is screen  at "/media/richard/HDD/General/web/_dev/gulp.com/node_modules/gulp-autoprefixer/index.js"
![screenshot from 2017-07-09 14-05-40](https://user-images.githubusercontent.com/26653363/27994032-1341e96a-64be-11e7-930a-51ce694baebf.png)

Nodejs version **8.1.3**
auro-prefixer **4.0.0**

How can I solve this problem?
thx

**Comment by kevva** [comment]
Can you log the error?

```js
.on('error', err => {
    console.log(err);
});
```

**Comment by richred** [comment]
Thank you, for answer. But мy problem disappeared after reinstallation
Ubutntu. And now it work :)

2017-07-10 12:12 GMT+03:00 Kevin Mårtensson <notifications@github.com>:

**Comment by roboriaan** [comment]
Here we go down the rabbit hole

**Comment by duzun** [comment]
@xumix just wander, what is in your ‘C:\Projects\Portal2’ folder? :)
I’m a fun of Portal2 game

**Comment by xumix** [comment]
@duzun oooops :) Not a game folder :)
