### ISSUE TITLE
autoprefixer().info() is not working

### ISSUE THREAD

**Issue by CharlesKumar** [sindresorhus/gulp-autoprefixer#86]
Actually this is not an issue/bug

I wonder how to know/debug what browsers are going to be prefixed by gulp-autoprefixer

is there any alternative way to know that information

**Comment by joshbuchea** [comment]
From [Debug section of Autoprefixer README](https://github.com/postcss/autoprefixer#debug):

> Run `npx autoprefixer --info` in your project directory to check which browsers are selected and which properties will be prefixed:

**Comment by CharlesKumar** [comment]
Thanks for your reply....

I have small doubt on how to interpret the result

> Browsers:
  Chrome for Android: 64
  Firefox for Android: 57
  And_qq: 1.2
  UC for Android: 11.8
  Android: 62, 4.4.3-4.4.4, 4.4
  Baidu: 7.12
  Chrome: 64, 63, 49
  Edge: 16, 15
  Firefox: 58, 57, 52
  IE: 11
  IE Mobile: 11
  iOS: 11.0-11.2, 10.3, 10.0-10.2
  Opera Mini: all
  Opera Mobile: 37, 12.1
  Opera: 50, 49
  Safari: 11, 10.1
  Samsung: 6.2, 5, 4

These browsers account for 91.73% of all users globally


The listed versions of the browsers going to be autoprefixed and  in case of   Chrome: 64, 63, 49 Firefox: 58, 57, 52

either chrome 49-64, firefox 52-57 (the entire range of browser versions) going to be autoprefixed or just account for the listed browsers.

or (autoprefixer uses data from caniuse afaik) there is no need to care, because the vendor prefixes are same for the entire range of browser versions

or only the listed versions are used globally (more) by the users

**Comment by CharlesKumar** [comment]
I might have expected a verbose cli output of what had happened during autoprefixing. Now I closing this because now it is out of concern for me.
