### ISSUE TITLE
Does not prefix css grid

### ISSUE THREAD

**Issue by jenstornell** [sindresorhus/gulp-autoprefixer#87]
Does not prefix css grid

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the Autoprefixer [issue tracker](https://github.com/postcss/autoprefixer/issues).*

**Comment by ShaggyDude** [comment]
Autoprefixer does support grid. gulp-autoprefixer does not seem to. This bug is in the right place imho
