### ISSUE TITLE
-webkit-flex-wrap: wrap is missing

### ISSUE THREAD

**Issue by weilinzung** [sindresorhus/gulp-autoprefixer#89]
on latest version of `gulp-autoprefixer` & `bootstrap 4 beta` is missing `-webkit-flex-wrap: wrap` after compile.

I tested on all IOS devices.
thanks!

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the Autoprefixer [issue tracker](https://github.com/postcss/autoprefixer/issues).*

**Comment by weilinzung** [comment]
also `display: -webkit-box;` is not correct, should be `display: -webkit-flex;`.

**Comment by weilinzung** [comment]
I think it is some of your `dependencies` in your package.json need to be updated.

**Comment by sindresorhus** [comment]
I think not. All dependencies are up to date.
