### ISSUE TITLE
gulp-load-plugins does not find autoprefixer

### ISSUE THREAD

**Issue by DanielRuf** [sindresorhus/gulp-autoprefixer#98]
I get an error that autoprefixer is not found when using gulp-autoprefixer with gulp-load-plugins but `npm ls autoprefixer` lists it.

**Comment by sindresorhus** [comment]
Open an issue on `gulp-load-plugins`. This is just a normal Gulp plugin. I don't see how it's an issue here.

**Comment by DanielRuf** [comment]
My guess is that it is due to a missing `main` entry in package.json.

I will probably create a small repo to reproduce this.
