### ISSUE TITLE
What are the breaking changes for 5.0.0?

### ISSUE THREAD

**Issue by adamreisnz** [sindresorhus/gulp-autoprefixer#99]
I'd like to update to 5.0.0 but can't find any documentation or change log for the breaking changes. Could you clarify what has changed?

**Comment by sindresorhus** [comment]
Major version bump of Autoprefixer: https://github.com/sindresorhus/gulp-autoprefixer/commit/78286463a149aa6d77be29e2a8f2ea878ebe2cf1

https://github.com/postcss/autoprefixer/releases/tag/8.0.0
